--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 10 2018 11:26
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'Person'   
-- PersonID        :  
-- FirstName       :  
-- MiddleName      :  
-- LastName        :  
-- ContactType     :  
--
CREATE TABLE Person (
    PersonID       INT NOT NULL IDENTITY,
    FirstName      VARCHAR(50) NOT NULL,
    MiddleName     VARCHAR(50) NULL,
    LastName       VARCHAR(50) NOT NULL,
    ContactType    VARCHAR(50) NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonID))